### PR TITLE
108 user can view updated navigation UI

### PR DESCRIPTION
**Pull request by Eoyie**
<h1>Main changes</h1>
Improved the look of the main navigation. Changed the navigation of both grower and retailer's page to work as tabs.

<h2>App.css</h2>

- Styling to make the offcanvas thinner. Actually just noticed this does not work after having moved the main navigation to components. Will be fixed.

<h2>NavigationBar.jsx</h2>

<h3>Navbar</h3>

- Added a button, which looks like a menu icon to open the offcanvas before the Navbar.Brand as the Navbar's own offcanvas would not allow "profile" and "language" to be left at "normal" navigation bar.
- Changed Navbar.Brand to work as a link to just "/", which currently links to /retailer or /grower based on default role (not sure if it should do this or just send to the homepage of the one open) and to /login.
- Removed Navbar collapsing as it would create two offcanvases.
- Navbar still piles up "profile" and "language" too early as expand="sm" is the smallest option and I could not get custom sizing to work.

<h3>Offcanvas</h3>

- Also has "Slowers" title, not sure if this should be changed. (not a link)
- Has links in a Nav flex-column. I think some of the styling could be improved here? just maybe adding lines, more spacing or link headers? Or maybe they should just be left as is.

<h2>GrowerLayout.jsx</h2>

- Updated from sidebar to work as tabs and to use bootstrap Nav instead of just nav.
- Added a placeholder for future user story. Currently not translated as I was not sure if it was needed? Currently links to home.

<h2>RetailerLayout.jsx</h2>

- Just a copy of GrowerLayout.jsx changed. Just noticed there is a left over defaultActiveKey="/grower" because of this. Will be changed.

<h2>SitePage.jsx</h2>

- Deleted styling before noticing the routing should be fixed. This component is not in use as it was updated to GrowerSitesPage.jsx so these changes should be just ignored.

<h1>Testing</h1>
I'm actually unsure if navigation should be tested or have any idea of how it could be tested. Is this more E2E than unit testing?

### CODE REVIEW

**Review by amandahamynen — COMMENTED** [review]
Good work! The UI looks much improved with these changes! I read your comment, and i’ll go ahead and fix the problem with App.css styling not being applied for NavigationBar.jsx, and remove the leftover ```dedaultActiveKey="/grower”``` from RetailerLayout.jsx. I also noticed unneccessary ```const { t, i18n } = useTranslation()``` in GrowerLayout and RetailerLayout, so i’ll be removing these as well.

I was thinking that maybe I could add the following changes as well;
- Remove the ’Go back’ button completely: it is no longer needed and behaves unexpectedly under some situations. For example, when user creates a subsite B inside a subsite A, then deletes subsite B and then clicks ’Go back’ in Subsite A’s sites-tab, there’s an error.
- Remove the text ’Site: {site.ID}’ from ’Home’ and ’Flowers’ tabs in subsites, since it was added just for debugging purposes for this task. It is no longer needed and looks unpolised, so it should be removed asap.
- Delete text ’Home’ from grower’s 'Home' and 'Flowers' tab
- Remove ’Home page’-link from the side navigation bar (Offcanvas), no longer needed as Slowers logo does that and is more intuitive to use.
- I was thinking should ’Log out’ be moved into the top navigation bar? In my opinion it would be more intuitive to use that way instead of it being hidden in Offcanvas

What do you think of the suggestions above? Would it be okay if i made them and pushed the changes into this PR?

**Comment by Eoyie** [comment]
Thank you for your review!

When it comes to the pages I think maybe the title of the issue is a little misleading. It was meant to only change the navigation parts so the top bars and add tabs so I have not edited any of the components (sitespage I only edited as I thought I would have to add the tabs there) themselves nor do I think I should.

I did think about deleting the home page from the offcanvas, but then I thought that essentially every website, even github still have the home link in the offcanvas. So I don't think it needs to be deleted.

I also thought about the logout part. But I feel like the logout button usually isn't the most visible functionality as generally the user doesn't need to logout that often. I did think about the profile part working as a dropdown and having "user settings" and "logout" there as I think that's also quite common? I'm not sure about this still.

**Comment by amandahamynen** [comment]
Alright, thanks for the reply! I fixed the minor things you mentioned originally, but I'll leave everything else as it is 👍 I think adding units tests at least for NavigationBar.jsx would be good, so it'd be nice if you'd add those before I approve this PR! :)

**Review by VSirvio — APPROVED** [review]
The menu items that were moved after the previous review work fine and also everything else still works great. All in all, the UI looks very nice now.

_This pull request will be exceptionally accepted, even though it doesn't have unit tests, because it turns out that the unit testing framework doesn't work very well with the navigation components added and modified in this pull request, and it seems that for that reason it would be very tricky to write unit tests for those components._

**Pull request merged**
