### PR TITLE
150 migrate from BrowserRouter to createBrowserRouter

### PR DESCRIPTION
**Pull request by Halmela**
# Migrate from BrowserRouter to createBrowserRouter
This pull request will migrate older implementation of react-router's BrowserRouter to a newer version.

> [!IMPORTANT]
> The day that this PR was finished, React-router v7 was published.
> Implementing it is out of this PR's scope and it is not mission critical for us.
 

## Motivation
When changing tabs in Site-page, every tab change refetches Site's information from the server.
This creates a small visible stutter with site's name and it started to bug me a little bit.
When I wanted to implement breadcrumb navigation for Sites, it dawned to me that the same fetching has to happen with every tab loading too, and it was enough to push me over to the edge.

React-router v6 introduces data-API, that allows routes to have dedicated [loaders](https://reactrouter.com/6.28.0/route/loader) and [actions](https://reactrouter.com/6.28.0/route/action), which allow routes and their components (and sub-routes/-components) to fetch and write dedicated state that persists over navigation.
This API also allows defining routes as an object instead of nested components.

Useful example and its visualization for data-API:
https://reactrouter.com/6.28.0/start/overview#nested-routes and https://remix.run/_docs/routing

## Implementation
My main materials for this migration were 
- [react-router upgrading to v6 guide](https://reactrouter.com/6.28.0/upgrading/v6-data) for general refactoring 
- [official authentication example](https://github.com/remix-run/react-router/tree/main/examples/auth-router-provider) for tuning how logins work
- [official router documentation](https://reactrouter.com/6.28.0/home)

Migrating to the newer version required moving a lot of state out of application's root, which is the reason for modifying so many files.
I will go through each file in the end of this PR, but here are the main design choices

#### Routing
Routes are now defined in `App.jsx`'s `router`.
Main route is `/`, its element is `NavigationBar`, loading it will refresh login information and every other route is its child.
Syntax for defining a route as an  object is different than a route, but the way they are work are still the same.
Main difference is that using loaders and actions is preferred over passing state as props and setters. 

#### Authenticating
Old way for managing login state was to store persistent information to local storage and then reflect those changes in `App.jsx` and then supply that information forward.

Now route `/` creates and uses `Authenticator`, which handles all logic for logging in and out and refreshing itself when needed. Components such as `NavigationBar` can access these loaded values with `useLoaderData()`.

### File changes
I have tried to keep component modifications to a minimum, but modifying logic relating to logins has been necessary.
Everything should look and act the same as before.

I suggest you read the Files changed -tab alongside this listing.

#### backend/handlers/user.go
`Authenticator` provides username, so it is returned here alongside token and role.

#### frontend/src/App.jsx
All state except translation service is moved out of the `Root`, and the only component here is `NavigationBar` wrapped in `Root`.
All routes are moved under one defined object, `router`.
`router` has same paths as the old `Router`, and it redirects all undefined paths to `/` which then are redirected to correct places.
> [!CAUTION]
> `/grower/:siteId` with an invalid id goes to a broken sitepage. Fixing this requires a dedicated loader for site, so I am wondering if this PR should introduce that loader as well.

Three loaders are defined:
- `roleLoader` redirects user to its rolepage, if they try to access `/login` or `/register` while logged in
- `protectedLoader` redirects unlogged user to `/login` if they try to access `/grower`, `/retailer` or `/user` 
- `rootLoader` redirects user from `/` to their home role page or `/login`
Site-loader will be created in another PR.

Two actions are defined:
- `POST /login` redirects user to `/` (cleaner way would be `Authenticator.login(data)` and then a redirect)
- `POST /logout` logs user out of `Authenticator`

#### frontend/src/Authenticator.jsx
Main login logic resides here.
This file defines an object that `router`'s `/`-route loads and then provides to all other paths.
Local storage is used for saving login information over page reloads.

#### frontend/src/components/LogInForm.jsx
Login logic is removed as part of form submit because it is handled elsewhere.

#### frontend/src/components/NavigationBar.jsx
`NavigationBar` loads login information from `root`-loader and uses it to display username and decide offcanvas content. Logout is implemented as internal action to `/logout`. This component is now an `Outlet` which means that it takes other components inside it and renders them.

#### frontend/src/components/ProtectedRoute.jsx
Removed as `protectedLoader` handles this now

#### frontend/src/pages/LogInPage.jsx
Logging in is done with the authenticator and fetcher-action is defined for reloading the page with new information after logging in.

#### frontend/src/pages/RegisterPage.jsx
Creating a new user logs new user in with the `Authenticator` and login-action is used. Navigation is done by the router.

#### frontend/src/pages/UserPage.jsx
Switcing user's role is now done with `Authenticator`.

---

This was quite big job, especially for the end of this project.
If we approve this PR, I will help everyone to define new routes and loaders if they are needed as the new concepts can be hard to grasp within our timeframe.

Please leave any comments if something needs clarifying.

### CODE REVIEW

**Review by VSirvio — CHANGES_REQUESTED** [review]
Looks very good!

A couple of small issues I found:
- App.jsx: Should line 97 have `GrowerHomePage` instead of `RetailerHomePage`? Though this doesn't seem to affect the functionality at all, so maybe this line could be removed altogether?
- I don't usually complain about minor formatting issues, but I think that at this point it would be a good idea to fix also all the smaller code formatting issues for the Route objects inside `createBrowserRouter()` and make the formatting consistent to set a good example for everyone modifying the routers in the future. E.g. for JavaScript objects that are too long for a single line, I would personally do something like
```javascript
{
    path: "retailer",
    element: <RetailerLayout />,
    children: [
        { ... },
        { ... },
    ],
}
```

A couple of questions that I think are worth considering about the general design:
- So if all flower and site data will be preloaded in the future and then stored inside the browser, how often will the page data be updated to reflect any possible changes in the database?
- Is bypassing the React props and accessing the Authenticator object directly from the components necessarily a good idea? This adds a new dependency to the components and generally having a smaller number of dependencies makes code easier to understand and test automatically etc., because the components can be then treated as independent units instead of as inseparable parts of a larger system.
- What is the advantage of storing the authentication data in the Authenticator object instead of just accessing the local storage every time? E.g. something like this
```javascript
export const Authenticator = {
    getUsername() {
        return localStorage.getItem("username")
    },
    ...
}
```

**Comment by Halmela** [comment]
> Looks very good and works great!

Thank you!


> A couple of small issues I found:
> 
>   App.jsx: Should line 97 have `GrowerHomePage` instead of `RetailerHomePage`? Though this doesn't seem to affect the functionality at all, so maybe this line could be removed altogether?

I have now corrected this.
Currently Retailer and Grower homepages are the same, but this can probably change in the future.
I would like to have different homepages for Grower and Grower's site, but for now this works.

>   I don't usually complain about minor formatting issues, but I think that at this point it would be a good idea to fix also all the smaller code formatting issues for the Route objects inside `createBrowserRouter()` and make the formatting consistent to set a good example for everyone modifying the routers in the future. E.g. for JavaScript objects that are too long for a single line, I would personally do something like
> 
> 
> ```js
> {
>     path: "retailer",
>     element: <RetailerLayout />,
>     children: [
>         { ... },
>         { ... },
>     ],
> }
> ```

I agree, the formatting has now been cleaned to some level. Splitting longer routes (such as `grower`) to their own files could also be a good idea.
 
> A couple of questions that I think are worth considering about the general design:
> 
>  So if all flower and site data will be preloaded in the future and then stored inside the browser, how often will the page data be updated to reflect any possible changes in the database?

Generally the data API way would be to load initial data for a route, submit an action for the same route and make the db-modifications etc. in the action-function. After the action has concluded, data will be loaded again.

Reloading data can also be triggered with a [fetcher](https://reactrouter.com/6.28.0/hooks/use-fetcher). Fetchers also allow accessing the formdata from previous requests, which then can be used to display information (new expected state or a loading element) on current component.

>  Is bypassing the React props and accessing the Authenticator object directly from the components necessarily a good idea? This adds a new dependency to the components and generally having a smaller number of dependencies makes code easier to understand and test automatically etc., because the components can be then treated as independent units instead of as inseparable parts of a larger system.

I agree that smaller number of dependencies is a good idea.

I removed any `Authenticator`-imports outside of `App.jsx`.
Here is a diff of the changes I made: [diff link](https://github.com/Slowers-Team/Slowers-App/pull/154/files/0f7b13563ad4b5f37d523087374673064077c79a..faa2f4f3dc8fd2a21a3a5e64a424eaffe74764bf)
The components that used `Authenticator` now make submit-actions to their respective paths and the actions perform the `Authenticator` mutations. This is not a good and consistent practice, but I have done the same job on three different levels, from cleanest to hackiest:
- Login is done with a `react-router-dom Form`, which submits login information to be fully processed by its corresponding action. If action returns any errors, they can be displayed in the form with `useActionData`. Testing is done with a predefined router. 
  - Note that `LoginForm` takes in no arguments and does not use `useState`
- Registering is done on the page level with `RegisterPage` contacting the userService and then making a submit to its path for performing `Authenticator` mutation.
- User role swithing is done in `UserPage` by combining local state mutations and a submit-action
> [!NOTE]
> I want to change all of these to work the same way as logging in, but I also want to demonstrate that it is possible to mix different state strategies, and because I want to write this comment tonight.


 

>  What is the advantage of storing the authentication data in the Authenticator object instead of just accessing the local storage every time? E.g. something like this
> 
> 
> ```js
> export const Authenticator = {
>     getUsername() {
>         return localStorage.getItem("username")
>     },
>     ...
> }
> ```

That is a good question.
I have not done any performance analysis if storing the state in `Authenticator` does any actual difference. The accesses to its fields are pretty rare, so the repetitive nature of it might not be justified.

**Comment by Halmela** [comment]
There is also [`useRevalidator`](https://reactrouter.com/6.28.0/hooks/use-revalidator), which revalidates state for any reason, such as part of a update request. I think using this might be the most ergonomic way for state reloading for components that have a complex state structure.

**Review by VSirvio — CHANGES_REQUESTED** [review]
I hate to suggest this, because you have made a lot of effort to still improve the authentication code after my comments, but I am still somewhat low on energy, I also have other things that I should get done at the moment, and the new improvements that you made to the authentication code are not really that high priority, so I would personally rather not spend any more time reviewing it and for that reason I would suggest leaving the improvements you made to the authentication code after my previous review out from this pull request.

Also, I would suggest using some automatic code formatter (such as Prettier) for the Route objects, because that is a more humane way of doing the formatting especially if we don't want to leave any formatting problems behind at all.

**Review by VSirvio — APPROVED** [review]
Everything looks good now!

**Pull request merged**
