### PR TITLE
13 fixing readme

### PR DESCRIPTION
**Pull request by VSirvio**
**Changes:**
- copy-paste installation instructions from example app
- links to documentation / project management
- link to staging server
- small introduction

### CODE REVIEW

**Comment by amandahamynen** [comment]
I suggest also adding instructions for using MongoDB Atlas. The instructions could go something along the lines of;

Option 2: Using MongoDB Atlas 


1. Create and login into your MongoDB Atlas account (https://account.mongodb.com/account/login)
2. Follow Go Driver Quick Start (https://www.mongodb.com/docs/drivers/go/current/quick-start/#std-label-golang-quickstart) to setup and connect your cluster
3. Save the connection string into .env file in the ’backend’ directory. Also add ’PORT=5001’ and ’ENV=development’. The file should look something like this:

```
MONGODB_URI=mongodb+srv://<username>:<password>@cluster0.am5gxap.mongodb.net/Slowers?retryWrites=true&w=majority&appName=Cluster0
PORT=5001
ENV=development
```

4. Inside the backend directory, start the app with the command ’go run main.go’
5. Open up a new terminal, and go into ’frontend’ directory. Install the dependencies and build the frontend using commands
```
npm install
npm run build
```
6. Now the application is running at http://localhost:5173/

The instructions above aren’t perfect, and need fact-checking and making sure they work 100%.

**Comment by VSirvio** [comment]
@amandahamynen Sounds good. Do you think we should also have instructions for starting the frontend separately in Vite with `npm run dev`, because at the moment there are only instructions for copying the frontend build to the backend directory and running the whole stack in the backend executable?

**Comment by amandahamynen** [comment]
Ah yes, apologies! It’s meant to have
```
npm run dev
```

Instead of 

```
npm run build
```

After that, the app should run in the frontend while the backend is running in the background :)

**Review by amandahamynen — COMMENTED** [review]
All good now! Excellent job! :)

**Pull request merged**
