### PR TITLE
24 api route for farm addition

### PR DESCRIPTION
**Pull request by Halmela**

### CODE REVIEW

**Comment by Halmela** [comment]
Allowing null values can create problems..

**Review by VSirvio — CHANGES_REQUESTED** [review]
Looks good! Here are a couple of questions that I thought were worth thinking about and also few minor formatting issues.

**Functionality:**
- Should `owner` be a required field?
- Should all growing sites in one hierarchy have the same owner? If so then should the owner be fetched from the parent growing site if there is one?
- Are the `log.Println` lines  in the `addSite` function meant to stay or were they just for the initial testing? (Just making sure)

**Coding style:**
- It would be better to make the indentation for the line `sites = client.Database("Slowers").Collection("sites")` consistent with the other lines.
- There is an extra empty line in
```golang
	} else {
		log.Println("created site", insertResult.InsertedID)

	}
```
- Could the `var sites *mongo.Collection` be renamed to `var siteCollection *mongo.Collection` for consistency?

**Comment by Halmela** [comment]
>     * Should `owner` be a required field?
Yes, it should. I have developed without the requirement, because it has speeded up my development (while taking technical debt).

>     * Should all growing sites in one hierarchy have the same owner? If so then should the owner be fetched from the parent growing site if there is one?
All sites having a same owner is a sane default and I think it would be good to check when adding new sites that owner of new site is same as the old site. One edge case is when adding a site without a parent, at least then the owner must be set (unless every user has a designated "root site").

>     * Are the `log.Println` lines  in the `addSite` function meant to stay or were they just for the initial testing? (Just making sure)
They are done for testing purposes, but I want to include them in production too because logging is best done proactively.
 
> **Coding style:**
Thanks, fixed.

**Review by VSirvio — APPROVED** [review]
Everything seems to be in order now.

**Pull request merged**
