### PR TITLE
83 backend function for fetching current user

### LINKED ISSUE #86: Separate ID validation from database usage
https://github.com/Slowers-Team/Slowers-App/blob/3156ddcc1cb7d1539fd5fb51879d494bff8453e1/backend/database/database.go#L19-L35

Currently some functions take IDs as `string`s and some take them as `ObjectID`s.
Validating and parsing a `string` to an `ObjectID` is not the responsibility of the database module but of the handler module.
The current functions should be converted to use only `ObjectID`s and tooling should be provided for easier usage in the future.
https://github.com/Slowers-Team/Slowers-App/issues/83#issue-2581038365 is one example of this.

Relevant reading:
- [Separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns)
- [Parse, don't validate](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/) This is written for Haskell, but the same concept of leveraging type system for gathering and validating information on processable data hold in Go, because they both are strongly typed.

### PR DESCRIPTION
**Pull request by Halmela**
This pull request adds two functions:
https://github.com/Slowers-Team/Slowers-App/blob/b837a237e9e05a2d9b406287853448f368786fd9/backend/database/database.go#L94-L103
which tries to parse an `ObjectID` from a `string`.

and

https://github.com/Slowers-Team/Slowers-App/blob/b837a237e9e05a2d9b406287853448f368786fd9/backend/handlers/handlers.go#L17-L32
which tries to fetch currently logged in user's ID from local context.

Rest of changes are converting the existing code to use these functions and making tests work.

I'd like to know, if the changes I made to tests are correct, because I am not confident in using testify.

Closes #86

### CODE REVIEW

**Review by VSirvio — CHANGES_REQUESTED** [review]
Well performed refactoring and I could not have made the unit test modifications better myself. I only have a couple of small suggestions.

**The old functions are still used in a couple of places:**
- `handlers/flower.go`: `AddFlower` still uses IsValidID and NewID for the site ID in the middle of the function
- `handlers/site.go`: `AddSite` still uses the old code instead of GetCurrentUser
- `NewID` and `IsValidID` functions can probably be removed from `database/database.go` after changing these

**This is a smaller thing and not absolutely necessary to change:**
- Return [primitive.NilObjectID](https://pkg.go.dev/go.mongodb.org/mongo-driver@v1.17.1/bson/primitive#ObjectID) instead of an uninitialized ObjectID variable from `ParseID` and `GetCurrentUser`. I think returning an explicit value should be preferred over returning an implicit value. Also then you could remove the comments from `GetCurrentUser`, because the code would be self-explanatory.
- Maybe even add `NilObjectID := primitive.NilObjectID` to `database/database.go` to define `database.NilObjectID` similarly to `database.ObjectID`, and use that.
- Use `database.ObjectID` instead of `primitive.ObjectID` in `GetCurrentUser`. My idea behind defining the type alias `database.ObjectID` for `primitive.ObjectID` was to hide the implementation details and make the `Database` interface potentially also usable for other databases than MongoDB.

**Comment by Halmela** [comment]
@VSirvio Thanks for the review, I applied your suggestions.
I removed the `IsValidID`, but left `NewID` intact, because tests relied on it and I couldn't create a more elegant solution for now.

**Review by VSirvio — CHANGES_REQUESTED** [review]
The `NilObjectID` matter looks good now. Nevertheless, I still have a couple of suggestions:
- `handlers/flower.go`: `AddFlower`: Instead of parsing `flower.Site.Hex()` to the `siteID` variable you could just use `flower.Site` directly. It is already of ObjectID type, so it is guaranteed to contain a valid object ID.
- `handlers/handlers.go`: `GetCurrentUser`: I think there is no need for the `var userID database.ObjectID` line anymore.

> I removed the `IsValidID`, but left `NewID` intact, because tests relied on it and I couldn't create a more elegant solution for now.

I don't think there is any more elegant way to do it by using the new `ParseID` than parsing the object ID string in the beginning of the function and saving it to a variable and then using that variable for the actual test data like this for example:
```golang
siteID, err := database.ParseID("66f5027d6430d371f8636c3c")
if err != nil {
	log.Fatal(err)
}

return []database.Site{
	{
		ID:        siteID,
...
```

For the flower IDs, you could do something like this to avoid unnecessarily repeating any code:
```golang
flowerIDStrs := []string{
	"842af389e234e768923475bc",
	"485a28e70545c378ff29b438",
	"ac83264ff67837e87eb82322",
}
flowerIDs := []database.ObjectID{}

for _, idStr := range flowerIDStrs {
	curFlowerID, err := database.ParseID(idStr)
	if err != nil {
		log.Fatal(err)
	}
	flowerIDs = append(flowerIDs, curFlowerID)
}

return []database.Flower{
	{
		ID:        flowerIDs[0],
...
```

**Comment by Halmela** [comment]
@VSirvio thanks for the comments, I implemented them in commit [1be20f6](https://github.com/Slowers-Team/Slowers-App/pull/90/commits/1be20f606a0596f86076863d7bd4986dfcd05edc).

**Review by VSirvio — APPROVED** [review]
Looks great and works great now!

**Pull request merged**
