### PR TITLE
148 user can see site images in the site flexbox

### LINKED ISSUE #148: User can see site images in the site flexbox
There was missing a feature that the grower can set an image to the site flexbox in the user story` #100 grower can manage site images`. The site flexbox  currently always displays only the placeholder image when creating a new site.

The placeholder image is displayed on the site flexbox automatically if the grower hasn't uploaded any image on the site. However if the grower has uploaded one image, it should be automatically displayed on the site flexbox. The grower can choose what image will be shown on the site flexbox if there are many image on the site.
<br />
<br />

_**Screenshot of the site flexbox's placeholder image:**_

image

<br />
<br />
<br />

_**Ideas how to implement this feature:**_

_Option 1:_  The site images are shown on the image carousel. There could be a button for each image to select the image to the site flexbox.

_Option 2:_ There could be a button "Edit" on the site flexbox itself where the grower can choose which image will be displayed on the flexbox.

### PR DESCRIPTION
**Pull request by Eoyie**
On this branch I've essentially added the same functionality to site images as in branches 161 and 162 we have done so for flower images. I have had to make a few changes:

- UpdateSite to simply set the site again, I'm not sure if I accidentally deleted some important functionality so I decided to keep this const rather than just writing SetSite everywhere where UpdateSite is called. The reason why this was done was, because I could not use .map on singular site objects.
- A requirement in the second GrowerImagePage.jsx UseEffect to wait for the site to be properly loaded as it was causing the site to be undefined on MarkFavorite without it.
- On SiteFlexbox.jsx added the requirement of sites existing for the UseEffect

I added some very simple rendering tests for Flexbox that technically don't test the image functionality here. I thought I should leave them as is, as I might change some things in the site styling improvements branch.

Closes #148

### CODE REVIEW

**Comment by Eoyie** [comment]
To note I'm not really addressing the site image styling here much, as I'm doing that on a separate branch.

**Review by VSirvio — CHANGES_REQUESTED** [review]
Nice work! Everything seems to be working great. I have only a couple of minor suggestions:
- I think the HTML attribute should be `className` instead of `classname`. It also shows errors for `classname` in the console.
- It would perhaps be nice if in the unit test for `SiteFlexbox` you tested that it shows the correct image.

**Comment by Eoyie** [comment]
Thank you for the review,

with the classNames I had already done the fix on another branch, so I did the same here to my understanding, but for some reason the case wasn't carried through the changes.

When it comes to the Flexbox tests, I honestly do not really want to make tests for this, as the flexbox will not be used again outside of this branch. I'll try to see if I can make tests for the replacement SiteMasonry on that branch. But I really see no reason to make tests for a component I know won't be used..

**Review by VSirvio — APPROVED** [review]
Looks good now! Implementing the unit tests can, in that case, be indeed left for a later pull request.

**Pull request merged**
